// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MultiRegGroupLasso_sigma_unified
List MultiRegGroupLasso_sigma_unified(const NumericMatrix& X_m, const NumericMatrix& Y_m, const IntegerMatrix& C_m, double lam1, double lam2, const NumericVector& sigma, Nullable<NumericMatrix> Phi_initial);
RcppExport SEXP _drfarm_MultiRegGroupLasso_sigma_unified(SEXP X_mSEXP, SEXP Y_mSEXP, SEXP C_mSEXP, SEXP lam1SEXP, SEXP lam2SEXP, SEXP sigmaSEXP, SEXP Phi_initialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X_m(X_mSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Y_m(Y_mSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type C_m(C_mSEXP);
    Rcpp::traits::input_parameter< double >::type lam1(lam1SEXP);
    Rcpp::traits::input_parameter< double >::type lam2(lam2SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type Phi_initial(Phi_initialSEXP);
    rcpp_result_gen = Rcpp::wrap(MultiRegGroupLasso_sigma_unified(X_m, Y_m, C_m, lam1, lam2, sigma, Phi_initial));
    return rcpp_result_gen;
END_RCPP
}
// MultiRegGroupLassoBIC
List MultiRegGroupLassoBIC(const NumericMatrix& X, const NumericMatrix& Y, const IntegerMatrix& C_m, const NumericVector& lam1_vec, const NumericVector& lam2_vec, const NumericVector& sigma, double gamma);
RcppExport SEXP _drfarm_MultiRegGroupLassoBIC(SEXP XSEXP, SEXP YSEXP, SEXP C_mSEXP, SEXP lam1_vecSEXP, SEXP lam2_vecSEXP, SEXP sigmaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type C_m(C_mSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lam1_vec(lam1_vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lam2_vec(lam2_vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(MultiRegGroupLassoBIC(X, Y, C_m, lam1_vec, lam2_vec, sigma, gamma));
    return rcpp_result_gen;
END_RCPP
}
// MultiRegGroupLassoDegree_sigma
List MultiRegGroupLassoDegree_sigma(const NumericMatrix& X_m, const NumericMatrix& Y_m, const IntegerMatrix& C_m, const NumericVector& lam1_vec, const NumericVector& lam2_vec, const NumericVector& sigma);
RcppExport SEXP _drfarm_MultiRegGroupLassoDegree_sigma(SEXP X_mSEXP, SEXP Y_mSEXP, SEXP C_mSEXP, SEXP lam1_vecSEXP, SEXP lam2_vecSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X_m(X_mSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Y_m(Y_mSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type C_m(C_mSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lam1_vec(lam1_vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lam2_vec(lam2_vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(MultiRegGroupLassoDegree_sigma(X_m, Y_m, C_m, lam1_vec, lam2_vec, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_drfarm_MultiRegGroupLasso_sigma_unified", (DL_FUNC) &_drfarm_MultiRegGroupLasso_sigma_unified, 7},
    {"_drfarm_MultiRegGroupLassoBIC", (DL_FUNC) &_drfarm_MultiRegGroupLassoBIC, 7},
    {"_drfarm_MultiRegGroupLassoDegree_sigma", (DL_FUNC) &_drfarm_MultiRegGroupLassoDegree_sigma, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_drfarm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
