# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MultiRegGroupLasso_sigma_unified <- function(X_m, Y_m, C_m, lam1, lam2, sigma, Phi_initial = NULL) {
    .Call('_drfarm_MultiRegGroupLasso_sigma_unified', PACKAGE = 'drfarm', X_m, Y_m, C_m, lam1, lam2, sigma, Phi_initial)
}

MultiRegGroupLassoBIC <- function(X, Y, C_m, lam1_vec, lam2_vec, sigma, gamma = 1.0) {
    .Call('_drfarm_MultiRegGroupLassoBIC', PACKAGE = 'drfarm', X, Y, C_m, lam1_vec, lam2_vec, sigma, gamma)
}

MultiRegGroupLassoDegree_sigma <- function(X_m, Y_m, C_m, lam1_vec, lam2_vec, sigma) {
    .Call('_drfarm_MultiRegGroupLassoDegree_sigma', PACKAGE = 'drfarm', X_m, Y_m, C_m, lam1_vec, lam2_vec, sigma)
}

